### ISSUE TITLE
Status of Conda ecosystem support

### ISSUE THREAD

**Issue by rgommers** [Quansight-Labs/free-threaded-compatibility#46]
- [x] Python itself and `pip` are now available in the `ad_testing` channel (builds on top of `defaults`): https://py-free-threading.github.io/installing_cpython/#conda
- [ ] conda-forge support (work not started yet)
- [ ] Issue with installing `noarch` packages in `conda` (& other installers): https://github.com/conda/conda/issues/14053

Currently (as of July 23rd, 2024) the recommended way to set up a conda dev environment for free-threaded CPython is to install `python` and `pip` from the `ad-testing` channel, and then install everything else from source or from nightly wheels.

**Comment by jjhelmus** [comment]
Conda-forge has a free-threading release of Python 3.13.0rc1: conda-forge/python-feedstock#679.

**Comment by lesteve** [comment]
FWIW the conda-forge command was added in #74 and is available in https://py-free-threading.github.io/installing_cpython/#conda-forge

**Comment by rgommers** [comment]
Conda-forge has had packages for a month or so now for both Python itself and for some key packages like `numpy` and `cython` (thanks to work by @isuruf). The `noarch` issue was also resolved, and a migrator is waiting to get started with larger-scale rebuilding once more projects have done a free-threading compatible release: https://conda-forge.org/status/migration/?name=python313t. So we're all good here for now.

I did a bit of automation to set up a Pixi dev environment for SciPy, that should translate pretty well to other packages with compiled code. If anyone needs it (extracted and cleaned up a bit from https://github.com/rgommers/pixi-dev-scipystack/blob/main/scipy/pixi.toml):

```toml
[feature.free-threading]
channels = ["conda-forge/label/cython_dev", "conda-forge"]

[feature.free-threading.dependencies]
python-freethreading = ">=3.13.0,<3.14"
compilers = ">=1.7.0,<2"
pkg-config = ">=0.29.2,<0.30"
ninja = ">=1.12.1,<2"
ccache = ">=4.10.1,<5"
meson = ">=1.6.0,<2"
meson-python = ">=0.16.0"
cython = ">=3.1.0a0,<4"
pythran = ">=0.17.0"
python-build = "*"
pip = "*"
blas-devel = "*"
numpy = ">=2.1.3"
pybind11 = ">=2.13.1"
pytest = "*"
hypothesis = "*"


[feature.free-threading.pypi-dependencies]
pytest-run-parallel = "*"

[feature.free-threading.tasks]
build-nogil = { cmd = "your-build-cmd", env = { CC = "ccache $CC", CXX = "ccache $CXX" } }
test-nogil = { cmd = "your-test-cmd" }
```
