### ISSUE TITLE
disabling build isolation not required to get nightly build dependencies

### ISSUE THREAD

**Issue by minrk** [Quansight-Labs/free-threaded-compatibility#55]
I've been following some of the guides here for pyzmq (working great so far!), and doing `--no-build-isolation` for one path was proving to be a bit of a pain.

I was able to avoid this by adding `--pre --extra-index-url https://pypi.anaconda.org/scientific-python-nightly-wheels/simple` to pip install to get the prereleases I needed without changing anything else about how things are installed.

In tests, I [did this](https://github.com/zeromq/pyzmq/pull/2006/files#diff-faff1af3d8ff408964a57b2e475f69a6b7c7b71c9978cccc8f471798caac2c88R142-R144) via PIP_PRE and PIP_EXTRA_INDEX_URL env in one "setup free-threading" step, so I didn't even need to modify the install command:

```bash
echo "PIP_PRE=1" >> "$GITHUB_ENV"
echo "PIP_EXTRA_INDEX_URL=https://pypi.anaconda.org/scientific-python-nightly-wheels/simple" >> "$GITHUB_ENV"
```

and [similar in cibuildwheel](https://github.com/zeromq/pyzmq/pull/2005/files#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711R197-R199) via build-frontend:

```toml
[[tool.cibuildwheel.overrides]]
select = "cp313t-*"
build-frontend = "pip; args: -v --pre --extra-index-url https://pypi.anaconda.org/scientific-python-nightly-wheels/simple"
```
