### ISSUE TITLE
`uv` appears to be working with 3.13t

### ISSUE THREAD

**Issue by jimkring** [Quansight-Labs/free-threaded-compatibility#97]
I noticed in this post: https://github.com/actions/setup-python/issues/771#issuecomment-2417544070

**Comment by henryiii** [comment]
Yes, `uv python install 3.13t` supports it (specifically [python-build-standalone](https://github.com/indygreg/python-build-standalone/issues/320) added it, which is what hatch, pdm, etc use too, and then uv added support for requesting it). uv itself has supported it since something like March.

**Comment by jimkring** [comment]
Thanks for confirming @henryiii

**Comment by jimkring** [comment]
@ngoldbaum I've been using `uv` pretty extensively in all my project and have had great success with it. It seems others in the community are having similarly positive experiences with it, too.

Side note, one of the things I've been LOVING about `uv` is that it supports editable local packages sources (e.g. local git submodules or vendored/copied package sources, which I sometimes prefer over `git+https://` remote package sources)

```toml
# pyproject.toml
[project]
dependencies = [
  "my-package-source",  # see below for local source code location.
]

[tool.uv.sources]
# this is like `cd submodules/my-package-source && pip install -e .`
my-package-source = { path = "submodules/my-package-source", editable = true }
```
